CREATE TABLE Users(
    Id UUID NOT NULL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    tax_number VARCHAR(15) NOT NULL UNIQUE,
    full_name VARCHAR(70) NOT NULL,
    Type VARCHAR(30) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    update_at DATETIME
)
